title: sensehat-scratch-mp3-player
hero_image: images/banner.png
description: sensehat-scratch-mp3-player description
version: 4
listed: false
copyedit: false
last_tested: "2018-05-29"
steps:
  - title: Introduction
  - title: Making it sparkle
  - title: Playing some tunes
  - title: Displaying the track number